### ISSUE TITLE
Code release date

### ISSUE THREAD

**Issue by HashmatShadab** [hila-chefer/Conceptor#1]
Hi

Thanks for sharing your work!

When can we expect for the codebase to be released?

**Comment by hila-chefer** [comment]
Hi @HashmatShadab, thanks for your interest!
Since this project was conducted as part of an internship, the code is in the process of internal approval before publishing. Once that’s done we will of course publish the code :)
Stay tuned :)

**Comment by hila-chefer** [comment]
Code is now live at:
https://github.com/google-research/google-research/tree/a2a0ec853e8fae38532c727799863e9d639aa0f2/conceptor

We will still provide support for issues and questions here as well :)
