### ISSUE TITLE
How can I obtain the vocabulary set V?

### ISSUE THREAD

**Issue by chkimmmmm** [hila-chefer/Conceptor#2]
Hello,
Thank you for sharing your work. 
I have a question about your paper that has brought me here. 
I'm curious about how you compiled the entire vocabulary set V mentioned in the paper and which dataset you used for this purpose.

Thank you!

**Comment by hila-chefer** [comment]
Hi @chkimmmmm thanks for your interest!

the code is now live at: https://github.com/google-research/google-research/tree/a2a0ec853e8fae38532c727799863e9d639aa0f2/conceptor
The vocabulary is simply the vocabulary from the CLIP text model, there are instructions in the code for how to do that :)

**Comment by chkimmmmm** [comment]
Thank you so much for your response!
